// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MapleService is the Wails-bound facade for MapleStory-specific
 * data. Currently exposes server status only; future expansion
 * (event list, character info) hangs here. Constructed once in
 * main.go and registered as a Wails service so the frontend can
 * call MapleService.ServerStatus().
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ServerStatus returns the latest cached probe result. Called by
 * the frontend via Wails IPC; the actual probe runs in the
 * background heartbeat goroutine (see NewMapleService).
 * @returns {$CancellablePromise<$models.Status>}
 */
export function ServerStatus() {
    return $Call.ByID(444633154).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Status.createFrom;
