// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoginService is the Wails-bound login facade. The frontend calls
 * StartQRLogin once, then polls CheckQRLogin every 2 seconds.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckQRLogin polls /QRLogin/CheckLoginStatus once and, on Approved,
 * runs the 4-call finalize handshake synchronously to acquire
 * bfWebToken. The frontend never sees the finalize step explicitly —
 * from its perspective a single CheckQRLogin call either stays Pending
 * or completes the login.
 * @returns {$CancellablePromise<$models.QRStatus>}
 */
export function CheckQRLogin() {
    return $Call.ByID(2498745925);
}

/**
 * GetAccounts returns the list of game accounts under the active
 * session. Requires StartQRLogin → CheckQRLogin to have completed
 * successfully (session != nil). See docs/beanfun-login-protocol.md § 8.
 * @returns {$CancellablePromise<$models.Account[]>}
 */
export function GetAccounts() {
    return $Call.ByID(3665416331).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Reset stops the keep-alive heartbeat and drops the cached client +
 * session. Used when an authenticated request comes back as
 * ErrSessionExpired so the next Snapshot returns nil and the
 * launcher service rejects further calls with ErrLoginRequired.
 * @returns {$CancellablePromise<void>}
 */
export function Reset() {
    return $Call.ByID(1458204088);
}

/**
 * Snapshot returns the current client + session pointers without a
 * copy. Used by sibling services (internal/launcher) that need to
 * drive post-login flows against the same cookie jar — the alternative
 * would be re-minting a client, which means re-logging-in.
 * 
 * Both returned pointers may be nil if no session is active; callers
 * must nil-check before use. The pointer-sharing is safe because:
 *   - BeanfunClient.http (and its cookie jar) is itself thread-safe.
 *   - Session is only mutated by LoginService under s.mu; readers
 *     observe a coherent snapshot of whichever Session was active at
 *     call time.
 * @returns {$CancellablePromise<[$models.BeanfunClient | null, $models.Session | null]>}
 */
export function Snapshot() {
    return $Call.ByID(917524005).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType3($result[0]);
        $result[1] = $$createType5($result[1]);
        return $result;
    }));
}

/**
 * StartQRLogin runs the init flow (getSessionKey → initQRLogin) and
 * returns the QR + deeplink for the frontend to render. A fresh
 * BeanfunClient (clean cookie jar) is minted on every call.
 * @returns {$CancellablePromise<$models.QRStart>}
 */
export function StartQRLogin() {
    return $Call.ByID(3663858381).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Account.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.BeanfunClient.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.Session.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.QRStart.createFrom;
