// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoginService is the Wails-bound login facade. The frontend calls
 * StartQRLogin once, then polls CheckQRLogin every 2 seconds.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckQRLogin polls /QRLogin/CheckLoginStatus once and, on Approved,
 * runs the 4-call finalize handshake synchronously to acquire
 * bfWebToken. The frontend never sees the finalize step explicitly —
 * from its perspective a single CheckQRLogin call either stays Pending
 * or completes the login.
 * @returns {$CancellablePromise<$models.QRStatus>}
 */
export function CheckQRLogin() {
    return $Call.ByID(2498745925);
}

/**
 * StartQRLogin runs the init flow (getSessionKey → initQRLogin) and
 * returns the QR + deeplink for the frontend to render. A fresh
 * BeanfunClient (clean cookie jar) is minted on every call.
 * @returns {$CancellablePromise<$models.QRStart>}
 */
export function StartQRLogin() {
    return $Call.ByID(3663858381).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.QRStart.createFrom;
