// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoginService is the Wails-bound login facade. The frontend calls
 * StartQRLogin once, then polls CheckQRLogin every 2 seconds.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckQRLogin returns Pending for the first two polls, then Approved.
 * That simulates a user scanning the QR around the 6-second mark
 * (3 polls × 2 s — matching pungin/Beanfun's cadence).
 * @returns {$CancellablePromise<$models.QRStatus>}
 */
export function CheckQRLogin() {
    return $Call.ByID(2498745925);
}

/**
 * StartQRLogin resets the mock state machine and returns a placeholder
 * QR bitmap + deeplink so the frontend has something to render.
 * @returns {$CancellablePromise<$models.QRStart>}
 */
export function StartQRLogin() {
    return $Call.ByID(3663858381).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.QRStart.createFrom;
