// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Account is one game account under the user's Beanfun ID. The
 * frontend uses these to render the post-login game list. See
 * docs/beanfun-login-protocol.md § 8.
 */
export class Account {
    /**
     * Creates a new Account instance.
     * @param {Partial<Account>} [$$source = {}] - The source object to create the Account.
     */
    constructor($$source = {}) {
        if (!("sid" in $$source)) {
            /**
             * SID identifies a real game account, so log it through MaskSID.
             * @member
             * @type {string}
             */
            this["sid"] = "";
        }
        if (!("ssn" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ssn"] = "";
        }
        if (!("sname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sname"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Account}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account(/** @type {Partial<Account>} */($$parsedSource));
    }
}

/**
 * BeanfunClient wraps a redirect-following http.Client plus a cookie
 * jar for a single Beanfun login session. A new instance starts a
 * fresh jar — no leftover cookies from a prior attempt.
 * 
 * One client (not two) is enough for our QR-only flow: step 6 of
 * finalize discards the response, and step 7 reads `bfWebToken`
 * from the jar after the redirect chain settles. See
 * docs/beanfun-login-protocol.md.
 */
export class BeanfunClient {
    /**
     * Creates a new BeanfunClient instance.
     * @param {Partial<BeanfunClient>} [$$source = {}] - The source object to create the BeanfunClient.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BeanfunClient instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BeanfunClient}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BeanfunClient(/** @type {Partial<BeanfunClient>} */($$parsedSource));
    }
}

/**
 * QRStart is the payload returned to the frontend when QR login begins.
 * BitmapBase64 is the QR PNG bytes encoded as base64 (no data: prefix).
 * Deeplink is the Beanfun mobile-app URL the QR encodes; surfaced so
 * the frontend can offer a "copy / open on phone" action.
 */
export class QRStart {
    /**
     * Creates a new QRStart instance.
     * @param {Partial<QRStart>} [$$source = {}] - The source object to create the QRStart.
     */
    constructor($$source = {}) {
        if (!("bitmapBase64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bitmapBase64"] = "";
        }
        if (!("deeplink" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deeplink"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QRStart instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QRStart}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QRStart(/** @type {Partial<QRStart>} */($$parsedSource));
    }
}

/**
 * QRState is the cached QR-login state. Error carries the rendered, credential-scrubbed message
 * when a poll or finalize failed, so the frontend keeps the needle it matches on today.
 */
export class QRState {
    /**
     * Creates a new QRState instance.
     * @param {Partial<QRState>} [$$source = {}] - The source object to create the QRState.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {QRStatus}
             */
            this["status"] = QRStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QRState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QRState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QRState(/** @type {Partial<QRState>} */($$parsedSource));
    }
}

/**
 * QRStatus mirrors the four outcomes Beanfun returns from
 * CheckLoginStatus, mapped to lower-case string tags so the TS side
 * gets a clean discriminated union.
 * @readonly
 * @enum {string}
 */
export const QRStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    QRStatusPending: "pending",
    QRStatusRetry: "retry",
    QRStatusExpired: "expired",
    QRStatusApproved: "approved",
};

/**
 * Session holds the credentials acquired after a successful login.
 * SKey and WebToken are session bearers — never log the struct with
 * %+v; use the redacted Stringer below. See
 * docs/beanfun-login-protocol.md § Token storage.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("SKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SKey"] = "";
        }
        if (!("WebToken" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["WebToken"] = "";
        }
        if (!("AccountID" in $$source)) {
            /**
             * empty for QR until GetAccounts runs (later milestone)
             * @member
             * @type {string}
             */
            this["AccountID"] = "";
        }
        if (!("ServiceCode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ServiceCode"] = "";
        }
        if (!("ServiceRegion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ServiceRegion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}
