// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * QRStart is the payload returned to the frontend when QR login begins.
 * BitmapBase64 is the QR PNG bytes encoded as base64 (no data: prefix).
 * Deeplink is the Beanfun mobile-app URL the QR encodes; surfaced so
 * the frontend can offer a "copy / open on phone" action.
 */
export class QRStart {
    /**
     * Creates a new QRStart instance.
     * @param {Partial<QRStart>} [$$source = {}] - The source object to create the QRStart.
     */
    constructor($$source = {}) {
        if (!("bitmapBase64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["bitmapBase64"] = "";
        }
        if (!("deeplink" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deeplink"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QRStart instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QRStart}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QRStart(/** @type {Partial<QRStart>} */($$parsedSource));
    }
}

/**
 * QRStatus mirrors the four outcomes Beanfun returns from
 * CheckLoginStatus, mapped to lower-case string tags so the TS side
 * gets a clean discriminated union.
 * @readonly
 * @enum {string}
 */
export const QRStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    QRStatusPending: "pending",
    QRStatusRetry: "retry",
    QRStatusExpired: "expired",
    QRStatusApproved: "approved",
};
