// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LauncherService is the Wails-bound facade for "click an account →
 * game launches with credentials filled". Two flows:
 * 
 *   - SpawnGame(account): fresh launch via argv (host port BeanFun
 *     SID OTP). Game auto-logs in to character select. Primary path.
 *   - Launch(account): inject credentials into an already-running
 *     game window via WM_CHAR. M8 path retained as a fallback for
 *     users who started the game outside our launcher.
 * 
 * State changes (started/exited) are reported asynchronously via the
 * gameStateChangedEvent Wails event.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as beanfun$0 from "../beanfun/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetGameState is the initial-state RPC the FE's useGameStateQuery
 * calls on mount. Subsequent updates arrive via the
 * gameStateChangedEvent push event, so this is read once per FE
 * lifecycle (per the queryClient cache). Probes findGameWindowFn
 * synchronously; cheap.
 * @returns {$CancellablePromise<$models.GameState>}
 */
export function GetGameState() {
    return $Call.ByID(4183131696).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetOTP runs the OTP fetch flow and returns the plaintext token for
 * display + clipboard copy on the frontend. The "show credentials so
 * the user can paste into another launcher" path that runs alongside
 * the direct-spawn SpawnGame method.
 * 
 * Two callers:
 *   - macOS dev verification: SpawnGame errors with platform-unsupported,
 *     so dev uses GetOTP + paste into a Windows Beanfun client (or
 *     just to confirm the wire format).
 *   - Windows users who prefer to launch the game through their own
 *     tooling rather than letting us spawn it.
 * 
 * The returned string lives in the frontend's JS heap (we can't zero
 * it from Go). Per Beanfun's design the OTP is single-use and
 * rotates on each call — keeping it in memory between fetch and
 * paste is acceptable given that single-use lifecycle.
 * @param {beanfun$0.Account} account
 * @returns {$CancellablePromise<string>}
 */
export function GetOTP(account) {
    return $Call.ByID(2873082354, account);
}

/**
 * Launch finds the running MapleStory window and injects the given
 * account's credentials into its login form via WM_CHAR (M8 path).
 * Used as a fallback when the user already has the game open from
 * outside our launcher — the argv-based SpawnGame can't help retroactively
 * since credentials must be passed at spawn time.
 * 
 * Returns:
 *   - LaunchResult{NoWindow: true} when no game window is open.
 *     FE handles this by re-querying GameState (the state may have
 *     just transitioned away).
 *   - LaunchResult{AutoFilled: true} on successful inject.
 *   - LaunchResult{AutoFilled: false, OTP: ...} when the window
 *     exists but inject failed mid-sequence — frontend shows the
 *     OTP for manual paste.
 * 
 * The OTP byte slice is zeroed before this method returns.
 * @param {beanfun$0.Account} account
 * @returns {$CancellablePromise<$models.LaunchResult>}
 */
export function Launch(account) {
    return $Call.ByID(1857854220, account).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SpawnGame fetches an OTP for the given account and spawns
 * MapleStory.exe with the canonical 5-arg positional argv that
 * triggers Gamania's auto-login path. Game.exe takes the OTP from
 * argv, validates server-side, and lands the user directly on
 * character select — no login form rendered, no WM_CHAR injection,
 * no form-ready timing window to navigate.
 * 
 * Returns when the spawn syscall has completed (typically <100ms);
 * the game's loading + server handshake + character-select render
 * happen afterward without the launcher's involvement. State
 * transitions (window-appeared, process-exited) reach the FE via
 * the gameStateChangedEvent push event, fired by the goroutine
 * kicked off via restartWatcher.
 * 
 * Errors and their FE handling:
 * 
 *   - ErrLoginRequired: session expired or absent. FE shows QR
 *     re-login.
 *   - errGameAlreadyRunning: defensive — FE should route to Launch
 *     when GameState.Running is true. Surface error directly.
 *   - resolveGameExe errors: registry value missing or override env
 *     var unset. Surface error directly.
 *   - spawn / FetchOTP errors: real failures. Surface error directly.
 * 
 * The OTP byte slice is zeroed via defer before this method returns,
 * matching the discipline of [[security-principles-beanfun]]. The
 * OS-side argv copy in the spawned process's memory is unavoidable
 * (kernel copies before we can scrub) but bounded by the OTP's
 * single-use server-side ticket lifetime.
 * @param {beanfun$0.Account} account
 * @returns {$CancellablePromise<void>}
 */
export function SpawnGame(account) {
    return $Call.ByID(4030112748, account);
}

// Private type creation functions
const $$createType0 = $models.GameState.createFrom;
const $$createType1 = $models.LaunchResult.createFrom;
