// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LauncherService is the Wails-bound facade for "click an account →
 * game window opens". Its single method, Launch, runs the post-login
 * OTP flow and spawns the game process with the OTP on the command
 * line. The OTP byte slice is zeroed immediately after spawn.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as beanfun$0 from "../beanfun/models.js";

/**
 * GetOTP runs the OTP fetch flow and returns the plaintext token for
 * display + clipboard copy on the frontend. This is the "show
 * credentials so the user can paste into another launcher" path that
 * pungin's UI exposes alongside the direct-spawn button.
 * 
 * Two callers:
 *   - macOS dev verification: the spawn path returns
 *     ErrPlatformUnsupported, so the user uses GetOTP + paste into a
 *     Windows Beanfun client (or just to confirm the wire format).
 *   - Windows users who prefer to launch the game through their own
 *     tooling rather than letting us spawn it.
 * 
 * The returned string lives in the frontend's JS heap (we can't zero
 * it from Go). Per Beanfun's design the OTP is single-use and
 * rotates on each call — this is acceptable for the same reason
 * pungin's UI is acceptable.
 * @param {beanfun$0.Account} account
 * @returns {$CancellablePromise<string>}
 */
export function GetOTP(account) {
    return $Call.ByID(2873082354, account);
}

/**
 * Launch fetches a one-time game-launch token for the given account
 * and spawns the game executable with `/hb /u:{SID} /p:{OTP}`. The
 * OTP byte slice is zeroed before this method returns regardless of
 * outcome.
 * 
 * Requires:
 *   - An active session (login → CheckQRLogin completed).
 *   - BEANFUN_GAME_EXE env var pointing at a valid game executable.
 * 
 * On Windows the spawn uses CreateProcessW; on non-Windows it returns
 * ErrPlatformUnsupported (the macOS dev box doesn't run game.exe).
 * @param {beanfun$0.Account} account
 * @returns {$CancellablePromise<void>}
 */
export function Launch(account) {
    return $Call.ByID(1857854220, account);
}
