// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LauncherService is the Wails-bound facade for "click an account →
 * game window opens". Its single method, Launch, runs the post-login
 * OTP flow and spawns the game process with the OTP on the command
 * line. The OTP byte slice is zeroed immediately after spawn.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as beanfun$0 from "../beanfun/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetOTP runs the OTP fetch flow and returns the plaintext token for
 * display + clipboard copy on the frontend. The "show credentials so
 * the user can paste into another launcher" path that runs alongside
 * the direct-spawn Launch method.
 * 
 * Two callers:
 *   - macOS dev verification: the spawn path returns
 *     ErrPlatformUnsupported, so the user uses GetOTP + paste into a
 *     Windows Beanfun client (or just to confirm the wire format).
 *   - Windows users who prefer to launch the game through their own
 *     tooling rather than letting us spawn it.
 * 
 * The returned string lives in the frontend's JS heap (we can't zero
 * it from Go). Per Beanfun's design the OTP is single-use and
 * rotates on each call — keeping it in memory between fetch and
 * paste is acceptable given that single-use lifecycle.
 * @param {beanfun$0.Account} account
 * @returns {$CancellablePromise<string>}
 */
export function GetOTP(account) {
    return $Call.ByID(2873082354, account);
}

/**
 * Launch finds the running MapleStory window and injects the given
 * account's credentials into its login form. Does NOT spawn the
 * game — see SpawnGame for that. Returns:
 * 
 *   - LaunchResult{NoWindow: true} when no game window is open.
 *     Frontend should prompt the user to press 啟動遊戲 first.
 *   - LaunchResult{AutoFilled: true} on successful inject.
 *   - LaunchResult{AutoFilled: false, OTP: ...} when the window
 *     exists but inject failed mid-sequence — frontend shows the
 *     OTP for manual paste.
 * 
 * The OTP byte slice is zeroed before this method returns.
 * @param {beanfun$0.Account} account
 * @returns {$CancellablePromise<$models.LaunchResult>}
 */
export function Launch(account) {
    return $Call.ByID(1857854220, account).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SpawnGame opens the configured MapleStory.exe but does not wait
 * for the login form. Returns nil when the game has been spawned
 * (or was already running).
 * 
 * Split out from Launch so the frontend can drive an explicit
 * two-step flow: user clicks 啟動遊戲 (this method) → waits visually
 * for the login form → clicks 帶入帳密 per account (Launch). That
 * design sidesteps the +20s "form input-ready" gap between window
 * visibility and the textbox actually accepting WM_CHAR; once the
 * user can see the form they're guaranteed it's ready, and inject
 * lands within ~100ms.
 * 
 * Requires:
 *   - An active session (so we know there's a logged-in user
 *     intending to play; resolveGameExe is independent of session).
 *   - Either BEANFUN_GAME_EXE env var or the registry value to
 *     locate the game executable.
 * @returns {$CancellablePromise<void>}
 */
export function SpawnGame() {
    return $Call.ByID(4030112748);
}

// Private type creation functions
const $$createType0 = $models.LaunchResult.createFrom;
