// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GameState mirrors the FE's gameStateAtom shape. JSON-tagged for
 * Wails event marshalling + GetGameState's RPC return.
 * 
 *   - Running=true with Hwnd>0 — watcher confirmed window present.
 *   - Running=true with Hwnd=0 — SpawnGame's spawnFn returned but
 *     window not yet detected (race window of ~0.5-4s before the
 *     game's first paint). FE treats this the same as the
 *     hwnd-known case.
 *   - Running=false — watcher detected exit, or app start probe
 *     found no game window.
 */
export class GameState {
    /**
     * Creates a new GameState instance.
     * @param {Partial<GameState>} [$$source = {}] - The source object to create the GameState.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["hwnd"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GameState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GameState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GameState(/** @type {Partial<GameState>} */($$parsedSource));
    }
}

/**
 * LaunchResult signals the outcome reported back to the frontend.
 * 
 *   - AutoFilled=true → the game's login form received the
 *     credentials. OTP empty (never exposed to frontend).
 * 
 *   - NoWindow=true → no game window is open. With M10.1's argv
 *     SpawnGame path this should be rare — FE only routes to Launch
 *     when GameState.Running is true. Returned anyway for defensive
 *     handling.
 * 
 *   - AutoFilled=false (NoWindow=false) → window was found but
 *     inject failed mid-sequence. OTP is populated so the frontend
 *     can offer the user manual-paste.
 * 
 * Hard errors (no session, OTP fetch failure) come back as a plain
 * Go error and never produce a LaunchResult.
 */
export class LaunchResult {
    /**
     * Creates a new LaunchResult instance.
     * @param {Partial<LaunchResult>} [$$source = {}] - The source object to create the LaunchResult.
     */
    constructor($$source = {}) {
        if (!("autoFilled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoFilled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["noWindow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["otp"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LaunchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LaunchResult(/** @type {Partial<LaunchResult>} */($$parsedSource));
    }
}
