// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LaunchResult is the outcome reported back to the frontend after a
 * successful spawn. Two states:
 * 
 *   - AutoFilled=true → window injection succeeded; the game's
 *     login form has been typed into and submitted. OTP stays "".
 *   - AutoFilled=false → spawn worked but the window-injection
 *     step failed (window class not found, PostMessage rejected,
 *     etc.). OTP is populated so the frontend can copy SID+OTP to
 *     the clipboard for manual paste.
 * 
 * A hard error (no session, missing game exe, spawn failure, OTP
 * fetch failure) is returned as a regular Go error and never
 * produces a LaunchResult.
 */
export class LaunchResult {
    /**
     * Creates a new LaunchResult instance.
     * @param {Partial<LaunchResult>} [$$source = {}] - The source object to create the LaunchResult.
     */
    constructor($$source = {}) {
        if (!("autoFilled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoFilled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["otp"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LaunchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LaunchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LaunchResult(/** @type {Partial<LaunchResult>} */($$parsedSource));
    }
}
