// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Kind selects how a Sound resolves to a playable target.
 * @readonly
 * @enum {string}
 */
export const Kind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    KindNone: "none",
    KindDefault: "default",
    KindBuiltin: "builtin",
    KindCustom: "custom",
};

/**
 * Option is one selectable row in the settings list.
 */
export class Option {
    /**
     * Creates a new Option instance.
     * @param {Partial<Option>} [$$source = {}] - The source object to create the Option.
     */
    constructor($$source = {}) {
        if (!("sound" in $$source)) {
            /**
             * @member
             * @type {Sound}
             */
            this["sound"] = (new Sound());
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("missing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Option instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Option}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sound" in $$parsedSource) {
            $$parsedSource["sound"] = $$createField0_0($$parsedSource["sound"]);
        }
        return new Option(/** @type {Partial<Option>} */($$parsedSource));
    }
}

/**
 * Selection is the currently selected sound plus whether it is playable.
 */
export class Selection {
    /**
     * Creates a new Selection instance.
     * @param {Partial<Selection>} [$$source = {}] - The source object to create the Selection.
     */
    constructor($$source = {}) {
        if (!("sound" in $$source)) {
            /**
             * @member
             * @type {Sound}
             */
            this["sound"] = (new Sound());
        }
        if (!("missing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Selection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Selection}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sound" in $$parsedSource) {
            $$parsedSource["sound"] = $$createField0_0($$parsedSource["sound"]);
        }
        return new Selection(/** @type {Partial<Selection>} */($$parsedSource));
    }
}

/**
 * Name holds a built-in file name and Path a custom absolute path.
 */
export class Sound {
    /**
     * Creates a new Sound instance.
     * @param {Partial<Sound>} [$$source = {}] - The source object to create the Sound.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {Kind}
             */
            this["kind"] = Kind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sound instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Sound}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Sound(/** @type {Partial<Sound>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Sound.createFrom;
