// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade over the alert-sound preference: it
 * composes the player (Play), the built-in catalogue (listBuiltinFn) and a
 * PrefsStore into the Options/Select/Preview/PlaySelected API the settings
 * page and the offline→online hook use.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Options lists none, Windows default, then the built-in catalogue.
 * @returns {$CancellablePromise<$models.Option[]>}
 */
export function Options() {
    return $Call.ByID(3621009290).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PlaySelected plays the current selection, falling back to KindDefault (and
 * logging a warning) when it is missing.
 * @returns {$CancellablePromise<void>}
 */
export function PlaySelected() {
    return $Call.ByID(16243303);
}

/**
 * Preview plays snd once without changing the selection.
 * @param {$models.Sound} snd
 * @returns {$CancellablePromise<void>}
 */
export function Preview(snd) {
    return $Call.ByID(622174480, snd);
}

/**
 * Select saves snd as the new selection, rejecting one Options() would not show.
 * @param {$models.Sound} snd
 * @returns {$CancellablePromise<void>}
 */
export function Select(snd) {
    return $Call.ByID(1032273868, snd);
}

/**
 * Selected returns the current selection and whether it is playable.
 * @returns {$CancellablePromise<$models.Selection>}
 */
export function Selected() {
    return $Call.ByID(2854372285).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Option.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Selection.createFrom;
