// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound facade over the alert-sound preference: it
 * composes the player (Play), the built-in catalogue (listBuiltinFn) and a
 * PrefsStore into the Options/Select/Preview/PlaySelected API the settings
 * page and the offline→online hook use.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCustom validates path as a WAV, adds it to the custom list (deduping by absolute path), and selects it as the current sound.
 * @param {string} path
 * @returns {$CancellablePromise<$models.Sound>}
 */
export function AddCustom(path) {
    return $Call.ByID(1680240028, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Options lists none, Windows default, then the built-in catalogue.
 * @returns {$CancellablePromise<$models.Option[]>}
 */
export function Options() {
    return $Call.ByID(3621009290).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * PlaySelected plays the current selection, falling back to KindDefault when
 * it is missing or when playback itself fails (a play failure on the
 * default is only logged, not retried).
 * @returns {$CancellablePromise<void>}
 */
export function PlaySelected() {
    return $Call.ByID(16243303);
}

/**
 * Preview plays snd once without changing the selection.
 * @param {$models.Sound} snd
 * @returns {$CancellablePromise<void>}
 */
export function Preview(snd) {
    return $Call.ByID(622174480, snd);
}

/**
 * RemoveCustom drops path from the custom list without touching the file on disk, falling the selection back to KindDefault if path was selected.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveCustom(path) {
    return $Call.ByID(766291359, path);
}

/**
 * Select checks and writes under one lock so a concurrent RemoveCustom cannot invalidate the check.
 * @param {$models.Sound} snd
 * @returns {$CancellablePromise<void>}
 */
export function Select(snd) {
    return $Call.ByID(1032273868, snd);
}

/**
 * Selected returns the current selection and whether it is playable.
 * @returns {$CancellablePromise<$models.Selection>}
 */
export function Selected() {
    return $Call.ByID(2854372285).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Sound.createFrom;
const $$createType1 = $models.Option.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Selection.createFrom;
